<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNkIJYc4\Glpi_Kernel_KernelProductionDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNkIJYc4/Glpi_Kernel_KernelProductionDebugContainer.php') {
    touch(__DIR__.'/ContainerNkIJYc4.legacy');

    return;
}

if (!\class_exists(Glpi_Kernel_KernelProductionDebugContainer::class, false)) {
    \class_alias(\ContainerNkIJYc4\Glpi_Kernel_KernelProductionDebugContainer::class, Glpi_Kernel_KernelProductionDebugContainer::class, false);
}

return new \ContainerNkIJYc4\Glpi_Kernel_KernelProductionDebugContainer([
    'container.build_hash' => 'NkIJYc4',
    'container.build_id' => 'b431612b',
    'container.build_time' => 1751994932,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNkIJYc4');
