version: "3.2"

services:
  glpi:
    image: diouxx/glpi
    container_name: glpi
    hostname: glpi
    ports:
      - "80:80"
    volumes:
      - ./glpi_data:/var/www/html/glpi
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
   #  environment:
   #    - TIMEZONE=Europe/Brussels # 
    env_file:
      - .env  # Esta línea carga las variables de entorno desde el archivo .env
    restart: always
